config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :create, :destroy] do
          resources :comments, only: [:index, :create, :destroy]
        end
      end
    end
  end
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', inverse_of: :posts
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  private

  def update_posts_counter
    author.increment!(:post_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_user, only: %i[index show create destroy]
  before_action :set_post, only: %i[show destroy]

  PER_PAGE = 3

  def index
    @posts = @user.posts.includes(:author).paginate(page: params[:page], per_page: PER_PAGE)
    render json: @posts
  end

  def show
    if @post
      render json: @post
    else
      render json: { error: 'Post not found' }, status: :not_found
    end
  end

  def create
    @post = Post.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.author = @user
    authorize! :create, @post
    if @post.save
      render json: @post, status: :created
    else
      render json: { error: 'Post creation failed' }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @post
    if @post.destroy
      render json: { message: 'Post deleted' }, status: :ok
    else
      render json: { error: 'Post deletion failed' }, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author).paginate(page: params[:page], per_page: 3)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
    user_id = params[:user_id].to_i

    return if current_user.id == user_id

    authorize! :create, @post
  end

  def create
    @post = Post.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    author = current_user
    @post.author = author
    if @post.save
      flash[:success] = 'Post successfully added!'
      redirect_to user_posts_path(current_user, @post)
    else
      flash.now[:error] = 'Post creation failed!'
      render :new
    end
  end

  def destroy
    user = current_user
    @post = Post.find_by(id: params[:id], author_id: params[:user_id])
    @post.comments.destroy_all
    @post.likes.destroy_all

    if @post.destroy
      flash[:notice] = 'Post deleted!'
    else
      flash[:alert] = 'Error! Please try again later.'
    end
    redirect_to user_posts_path(user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_post.html.erb
<article class='post'>
  <h3 class='post-title'><%= link_to_unless_current "#{post.title}", user_post_path(@user, post)%></h3>
  <p><%= truncate(post.text, length: 200, separator: ' ', omission: '...') %></p>
  <div class='post-comments-likes'>
    <span class='post-comments-count'>Comments: <%= post.comments.count%></span>
    <span class='post-likes-count'>&nbsp;&nbsp;&nbsp;Likes: <%= post.likes.count%></span>
  </div>
</article>

app/views/posts/_post_details.html.erb
<article class='post'>
  <h3 class='post-title'><%= "#{post.title} by #{post.author.name}"%></h3>
  <div class='post-comments-likes'>
    <span class='post-comments-count'>Comments: <%= post.comments.count%></span>
    <span class='post-likes-count'>&nbsp;&nbsp;&nbsp;Likes: <%= post.likes.count%></span>
  </div>
  <p class='post-text'><%= post.text %></p>
</article>

app/views/posts/index.html.erb
<div class="user-posts">
  <%= render @user %>
  <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  <% end %>
  <% if @user == current_user %>
    <div>
      <%= link_to "Creat New post", new_user_post_path %>
    </div>
  <% end %>
  <% if @user.posts.empty? %>
    <p class="empty-message">This user has not written any posts!!!</p>
  <% else %>
    <% @posts.includes(:author).each do |post| %>
      <%= render post%>
      <% unless post.recent_comments.empty? %>
        <h4 class="users-comments">
          <% post.recent_comments.each do |comment| %>
            <%= "#{comment.author.name}: #{comment.text}" %><br>
          <% end %>
        </h4>
      <% end %>
    <% end %>
    <%= will_paginate @posts %>
  <% end%>
</div>

app/views/posts/new.html.erb
<div>
  <h1>Create a new post</h1>
  <% if flash[:error] %>
    <div class="alert alert-error">
      <%= flash[:error] %>
    </div>
  <% end %>
  <div class='create-post'>
    <%= form_with model: @post, url: user_posts_path, method: :post, data: { turbo: false } do |form| %>
      <%= form.label :title, 'Title', class: 'post_label' %>
      <%= form.text_field :title, class: 'post_title' %>
      <%= form.label :text, 'Text', class: 'post_label' %>
      <%= form.text_area :text, class: 'post_textarea' %>
      <%= form.submit %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div style="width:90%; margin-top: 2rem;">
  <%= render partial: "posts/post_details", locals: {post: @post} %>
  <div class="actions">
    <% if can? :destroy, @post %>
      <%= button_to 'Delete post', user_post_path(@post.author, @post), method: :delete, class: 'actions__button' %>
    <% end %>
    <%= link_to 'Add a new comment', new_user_post_comment_path(@user, @post), class: 'actions__button' %>
    <%= button_to 'Like', user_post_likes_path(@user, @post), method: :post, class: 'actions__button' %>
  </div>
  <% unless @post.comments.empty? %>
    <h4 class="users-comments">
      <% @post.comments.includes(:post).each do |comment| %>
        <%= "#{comment.author.name}: #{comment.text}" %><br>
        <% if can? :destroy, comment %>
          <%= button_to 'Delete comment', user_post_comment_path(comment.author, @post, comment ), method: :delete, class: 'actions__button' %>
        <% end %>
        <br>
      <% end %>
    </h4>
  <% end %>
</div>