config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :create, :destroy] do
          resources :comments, only: [:index, :create, :destroy]
        end
      end
    end
  end
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'user', media: 'all' %>
    <%= stylesheet_link_tag 'new-post', media: 'all'%>
    <%= stylesheet_link_tag 'comment', media: 'all'%>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="navbar">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong> |
        <%= link_to "Home", users_path, class: "navbar-link" %> |
        <%= link_to "Profile", user_path(current_user), class: "navbar-link" %> |
        <%= link_to "Posts", user_posts_path(current_user), class: "navbar-link" %> |
        <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>